steps:
# Build Docker Image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/sit323-23t1-randhawa-dbfe268/arandhawa98/helloworld:$COMMIT_SHA', '.']


# Docker Push
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/sit323-23t1-randhawa-dbfe268/arandhawa98/helloworld:$COMMIT_SHA']


- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/mydeployment', 'mynode=gcr.io/sit323-23t1-randhawa-dbfe268/arandhawa98/helloworld:$COMMIT_SHA']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=australia-southeast2-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=calculatorapp-cluster'

